### PR TITLE
Display thumbnail after saving

### PR DESCRIPTION
**Pull request by xinan**
1. Calculate the actual image size and location, copy and redraw it to a 128x128 temporary canvas. 
2. Convert the temporary canvas to a data url, which is easy to embed in html, as well as easy to transfer to the server. 
3. Display the thumbnail in a tooltip below the "save" button after saving. Auto close after 3 seconds. 

Run `grunt` or `grunt less` to update the css. 

screenshot
(I learnt this fractal from David's blog :grin: It's cool :+1:)

Known problem:
When it saves, it actually captures what is in the output region at that moment. So if saving is performed before the program is being run, then it will capture nothing expect that little cute turtle :stuck_out_tongue:

### CODE REVIEW

**Comment by weihang7** [comment]
LGTM. In light of the known issue that you mentioned, would it be beneficial to either save a "cache output" for a program or automatically run a program when it is opened for editing?

**Comment by xinan** [comment]
Some program takes super long to run, like the one in the screenshot above. So run it automatically might not be a very good idea I think.

**Comment by davidbau** [comment]
Xinan, can you separate this into two PRs, one for server-only changes, and the other for the client changes?  Let's take a look at the server-only PR first.

**Comment by xinan** [comment]
This was just a test branch for debugging test cases on Travis. It can be closed now.

**Comment by davidbau** [comment]
Thanks xinan!

**Comment by xinan** [comment]
:smile: np

**Pull request closed without merging**
