### PR TITLE
[WIP] Add image optimizing into building process

### PR DESCRIPTION
**Pull request by xinan**
###### Reduced the overall size of all the images by 22%

Pros:
* Can reduce site loading time, improve performance. 
* Can save bandwidth for the server in the long run. 

Cons:
* Increased repo size by 2MB because old images are still in the history. (Maybe someone knows how to clean it)

I'm not sure whether this is a good decision or not. Since images are usually cached. So the improvement in loading time and the saving of bandwidth might not be very significant. Is it worth the increase of 2MB in repo size? Anyway, it is better to optimise images before adding them to the repo in the future. 

Please share your thoughts. Thank you!

### CODE REVIEW

**Comment by davidbau** [comment]
Hey there - a question about this 22% reduction - was it lossless or lossy?  Do you have a tool that can be used to optimize the images in the future?

For example, all the images in that directory have been pngcrushed using the "crushall.sh" script in that directory.  Could you replace "crushall" to reduce the images in this better way?

**Comment by xinan** [comment]
It was lossless. 
The tool I used was [ImageOptim](https://imageoptim.com). It integrates several image optimising tools including PngCrush. It has some command line tools [here](https://imageoptim.com/command-line.html). I will try to integrate it into the build process. Maybe using something like [grunt-imageoptim](https://github.com/JamieMason/grunt-imageoptim).

**Comment by davidbau** [comment]
Nice.  If you are able to make a self-contained build that does the optimization, that is great.

However, if it's messy, then it would be OK to check in a shell script to do the optimization (to be run whenever adding images), along with instructions on how to manually install whatever is necessary to run the script.

**Comment by xinan** [comment]
Sorry. Final exam period. This will be postponed for awhile. :stuck_out_tongue:

**Comment by davidbau** [comment]
No problem.  Just ping again when you have time to look at it.

**Comment by xinan** [comment]
Exams just ended. Will look at this in the following a few days.

**Comment by davidbau** [comment]
Great - thanks!

**Comment by xinan** [comment]
Since `ImageOptim` is only available on Mac OS X, I've decided to use `imagemin` instead. There is a grunt plugin for it called `grunt-contrib-imagemin`. I've integrated it into the project, added it into the default `grunt` task and used it to optimize the existing images. 

However, the `imagemin` failed to install on Travis CI which I haven't figured out why :open_mouth: 
One possible reason might be that Travis CI is using `npm v1.4.28` whereas I'm using `npm v2.7.5`.

**Comment by davidbau** [comment]
Thanks!   Travis-ci is working for me, even though it's got the older npm version.  Merged.

**Pull request merged**
